scan_filter_chain:
- name: ranges
  type: laser_filters/LaserScanRangeFilter
  params:
    lower_threshold: 0.17
- name: shadows
  type: laser_filters/ScanShadowsFilter
  params:
    min_angle: 10
    max_angle: 170
    neighbors: 10
    window: 1
